{
  "vocab-file": "/cognitive_comp/common_data/LLamaTokenizer_7B/",
  "save": "/cognitive_comp/yangping/checkpoints/llama/llama_13B_continue_pretrained/checkpoints",
  "load": "/cognitive_comp/yangping/checkpoints/llama/llama_13B_continue_pretrained/checkpoints_v4",
  "megatron_config_path": "/cognitive_comp/yangping/nlp/gpt-neox/workspace/llama/config_megatron/13b_generate_config.json",

  "launcher": "slurm",
  "deepspeed_slurm": false,
  "global_num_gpus": 16,
  "finetune": true,
  "eod_mask_loss": true,
  "load_module_only": true,

  "sample_input_file": "/home/yangping/nlp/gpt-neox/workspace/llama/generate/commonsense.txt",
  "sample_output_file": "/home/yangping/nlp/gpt-neox/workspace/llama/generate/commonsense.json",
  "maximum_tokens": 512,
  "temperature": 0,
  "top_p": 0.85,
  "recompute": True,

  "scaled-upper-triang-masked-softmax-fusion": false,
  "scaled_masked_softmax_fusion": true,
  "attention_softmax_in_fp32": true,

  "pipe-parallel-size": 4,
  "model-parallel-size": 1,

  "num-layers": 40,
  "hidden-size": 5120,
  "num-attention-heads": 40,
  "seq-length": 512,
  "max-position-embeddings": 2048,
  "norm": "llamarmsnorm", # neox layernorm
  "rms_norm_epsilon": 1.0e-6,
  "pos-emb": "rotary",
  "rotary_pct": 1,
  "no-weight-tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "bias-gelu-fusion": false,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "mlp_type": "llama",
  "activation": "swish",
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",

  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 3.0e-5,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
      }
      },

  "min_lr": 1.0e-5,
  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },
  "train_micro_batch_size_per_gpu": 4,
  "gradient_accumulation_steps": 8,
  "data-impl": "mmap",
  "split": "995,4,1",

  "checkpoint-activations": true,
  "checkpoint-num-layers": 1,
  "partition-activations": false,
  "synchronize-each-layer": true,

  "gradient_clipping": 1.0,
  "weight-decay": 0.1,
  "hidden-dropout": 0,
  "attention-dropout": 0,

  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
    },

  "train-iters": 4792,
  "lr-decay-iters": 4792,

  "distributed-backend": "nccl",
  "lr-decay-style": "cosine",
  "warmup": 0.06,
  "checkpoint-factor": 1000,
  "eval-interval": 200000,
  "eval-iters": 100,

  "log-interval": 2,
  "steps_per_print": 2,
  "wall_clock_breakdown": false,

  "tokenizer_type": "HFLlamaTokenizer",
  "tensorboard-dir": "../tensorboard_13b",
  "log-dir": "../log_13b",
  "checkpoint_validation_with_forward_pass": false
}
