{
  "vocab-file": "/cognitive_comp/common_data/LLamaTokenizer_7B/",
  "save": "/cognitive_comp/yangping/checkpoints/llama/llama_13B_continue_pretrained/checkpoints_v4",
  "load": "/cognitive_comp/yangping/checkpoints/llama/llama_13B_continue_pretrained/checkpoints_v4",
  "megatron_config_path": "/cognitive_comp/yangping/nlp/gpt-neox/workspace/llama/config_megatron/13b_config.json",

  "train-data-paths": ["/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/zijian/data_content_document","/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/wudao/data_content_document","/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/openwebtext/data_text_document","/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/github/data_text_document","/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/books/data_text_document","/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/wiki_en/data_text_document"],
  "test-data-paths": ["/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/test/data_text_document"],
  "valid-data-paths": ["/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/val/data_text_document"],
  "train-data-weights": [13712478,19638395,8173389,15899141,1238132, 2686451],
  "test-data-weights": [1.],
  "valid-data-weights": [1.],

  "train-indexmap-data-paths": ["/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/zijian/data_content_document","/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/wudao/data_content_document","/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/openwebtext/data_text_document","/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/github/data_text_document","/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/books/data_text_document","/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/wiki_en/data_text_document"],
  "test-indexmap-data-paths": ["/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/test/data_text_document"],
  "valid-indexmap-data-paths": ["/cognitive_comp/yangping/data/pretrain_corpus/llama_continue_pretraining/val/data_text_document"],

  "use_wandb": true,
  "wandb_project": "llama_13b_continue_pretrain_v3",
  "wandb_group": "llama_13b_continue_pretrain_v3",
  "wandb_team": "fengshenbang",
  "launcher": "slurm",
  "deepspeed_slurm": false,
  "global_num_gpus": 160,

  "eod_mask_loss": true,
  "reset_attention_mask": true,
  "reset_position_ids": true,

  "scaled-upper-triang-masked-softmax-fusion": false,
  "scaled_masked_softmax_fusion": true,
  "attention_softmax_in_fp32": true,

  "pipe-parallel-size": 4,
  "model-parallel-size": 1,

  "num-layers": 40,
  "hidden-size": 5120,
  "num-attention-heads": 40,
  "seq-length": 2048,
  "max-position-embeddings": 2048,
  "norm": "llamarmsnorm", # neox layernorm
  "rms_norm_epsilon": 1.0e-6,
  "pos-emb": "rotary",
  "rotary_pct": 1,
  "no-weight-tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "bias-gelu-fusion": false,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "mlp_type": "llama",
  "activation": "silu",
  "init_method": "small_init",
  "output_layer_init_method": "wang_init",
  "override_lr_scheduler": true,
  "use_checkpoint_lr_scheduler": false,
  "optimizer": {
    "type": "Adam",
    "params": {
      "lr": 1.0e-7,
      "betas": [0.9, 0.95],
      "eps": 1.0e-8
      }
      },

  "min_lr": 1.0e-7,
  "zero_optimization": {
    "stage": 1,
    "allgather_partitions": true,
    "allgather_bucket_size": 500000000,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 500000000,
    "contiguous_gradients": true
  },
  "train_micro_batch_size_per_gpu": 4,
  "gradient_accumulation_steps": 8,
  "data-impl": "mmap",
  "split": "995,4,1",

  "checkpoint-activations": true,
  "checkpoint-num-layers": 1,
  "partition-activations": false,
  "synchronize-each-layer": true,

  "gradient_clipping": 1.0,
  "weight-decay": 0.1,
  "hidden-dropout": 0,
  "attention-dropout": 0,

  "fp16": {
    "fp16": true,
    "enabled": true,
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 12,
    "hysteresis": 2,
    "min_loss_scale": 1
    },

  "train-iters": 47920,
  "lr-decay-iters": 47920,

  "distributed-backend": "nccl",
  "lr-decay-style": "cosine",
  "warmup": 0.025,
  "checkpoint-factor": 200,
  "eval-interval": 200,
  "eval-iters": 20,

  "log-interval": 2,
  "steps_per_print": 2,
  "wall_clock_breakdown": false,

  "tokenizer_type": "HFLlamaTokenizer",
  "tensorboard-dir": "../tensorboard_13b",
  "log-dir": "../log_13b",
  "checkpoint_validation_with_forward_pass": false
}
