python /cognitive_comp/wuziwei/codes/gpt-neox/tools/preprocess_data.py \
            --input /cognitive_comp/common_data/big_corpus/chatGPT/zh_unsup.jsonl \
            --jsonl-keys content \
            --output-prefix /cognitive_comp/wuziwei/task/academicGPT/ftfy_zh_unsup/zh_unsup \
            --vocab /cognitive_comp/common_data/BPETokenizer-Mix-NEO-pre \
            --dataset-impl mmap \
            --tokenizer-type HFGPTNeoXTokenizerFast \
            --workers 32 \
            --append-eod \
            --log-data \
            --ftfy